# Generated by Django 3.1.3 on 2022-01-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=None)),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
